### ISSUE TITLE
OutOfMemory after adding 8k+ user rule 

### ISSUE THREAD

**Issue by condesales** [launchdarkly/android-client#18]
In my currently scenario, I had to handpick some of my app users myself and add them with an API script I've created in order to add them to a specific flag.

Soon after the script finished, I started receiving crash reports for OutOfMemory with launchDarkly artifact id on it.

```java
Fatal Exception: java.lang.OutOfMemoryError: Could not allocate JNI Env
       at java.lang.Thread.nativeCreate(Thread.java)
       at java.lang.Thread.start(Thread.java:1063)
       at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:921)
       at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1339)
       at com.launchdarkly.eventsource.AsyncEventHandler.onMessage(AsyncEventHandler.java:31)
       at com.launchdarkly.eventsource.EventSource.com.launchdarkly.eventsource.EventParser.dispatchEvent(EventSource.java:9080)
       at com.launchdarkly.eventsource.EventSource$1.run(EventSource.java:69)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
```

Other crashes are being reported for the same reason in different parts of the code, but I guess the reason is the same.

Why would that happen? It doesn't make any sense to me, but I reckon it's probably not a coincidence. 
When launchDarkly fetches the flags, does the response contains all users added in a rule for a specific flag?

**Comment by drichelson** [comment]
@condesales do you mind emailing support@launchdarkly.com and we can continue there?

**Comment by condesales** [comment]
@drichelson not at all. Will move to email instead
